### ISSUE TITLE
Rename python library to lowercase (robotframework-openshiftcli)?

### ISSUE THREAD

**Issue by jgarciao** [red-hat-data-services/robotframework-OpenShiftCLI#1]
I believe the python library name should be lowercase (robotframework-openshiftcli) according to the [python style guide](https://www.python.org/dev/peps/pep-0008/#package-and-module-names): 

![image](https://user-images.githubusercontent.com/66894/132820444-ad5240f0-1453-4631-8d85-f6e131daabd8.png)

https://github.com/red-hat-data-services/robotframework-OpenShiftCLI/blob/192bf3552a92b8d88d05cf36754e332bba671b3d/setup.py#L26

**Comment by pablofelix** [comment]
renamed
